//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whatsapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WhatsappDBEntities : DbContext
    {
        public WhatsappDBEntities()
            : base("name=WhatsappDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_book> tbl_book { get; set; }
        public virtual DbSet<tbl_bookinfor> tbl_bookinfor { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
    }
}
