//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whatsapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_book
    {
        public int ID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> MessageID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string SenderName { get; set; }
        public string Message { get; set; }
        public Nullable<int> ImageId { get; set; }
    
        public virtual tbl_bookinfor tbl_bookinfor { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
