//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whatsapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bookinfor
    {
        public int BookInfoID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FrontTitle { get; set; }
        public string BackTitle { get; set; }
        public byte[] Image { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
